# Generated by Django 5.2.3 on 2025-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_participants_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
        ),
    ]
